const cocktailsData = [
  {
    id: 1,
    name: "莫吉托",
    nameEn: "Mojito",
    base: "白朗姆酒",
    baseEn: "Rum",
    ingredients: "白朗姆酒 45ml、青柠汁 20ml、薄荷叶 6-8 片、糖浆 15ml、苏打水补满",
    steps: "薄荷叶 + 青柠 + 糖浆轻捣，加冰、朗姆酒摇匀，倒入杯，补苏打水",
    flavor: "清新酸甜、薄荷凉感，青柠果香突出，清爽解腻",
    tags: ["清新", "酸甜", "经典"]
  },
  {
    id: 2,
    name: "自由古巴",
    nameEn: "Cuba Libre",
    base: "白朗姆酒",
    baseEn: "Rum",
    ingredients: "白朗姆酒 45ml、青柠汁 15ml、可乐补满",
    steps: "加冰，入朗姆、青柠汁，倒可乐至满，轻搅",
    flavor: "可乐甜香 + 朗姆醇厚，酸甜微苦，顺口易饮",
    tags: ["经典", "易饮", "甜美"]
  },
  {
    id: 3,
    name: "金汤力",
    nameEn: "Gin Tonic",
    base: "金酒",
    baseEn: "Gin",
    ingredients: "金酒 45ml、汤力水补满、青柠角",
    steps: "加冰，入金酒，倒汤力水，轻搅，青柠装饰",
    flavor: "杜松子草本香，汤力微苦回甘，清爽干爽",
    tags: ["经典", "清爽", "干爽"]
  },
  {
    id: 4,
    name: "威士忌酸",
    nameEn: "Whiskey Sour",
    base: "威士忌",
    baseEn: "Whiskey",
    ingredients: "威士忌 45ml、柠檬汁 25ml、糖浆 15ml、蛋清 1 份（可选）",
    steps: "所有材料加冰摇匀，滤入杯，柠檬装饰",
    flavor: "威士忌醇厚，酸甜平衡，口感顺滑柔和",
    tags: ["酸酒", "经典", "顺滑"]
  },
  {
    id: 5,
    name: "曼哈顿",
    nameEn: "Manhattan",
    base: "威士忌",
    baseEn: "Whiskey",
    ingredients: "黑麦/威士忌 50ml、甜苦艾酒 15ml、安哥斯图拉苦精 1 滴",
    steps: "加冰搅拌至冰杯，滤入杯，樱桃装饰",
    flavor: "威士忌浓郁醇厚，微甜回甘，酒体偏烈",
    tags: ["经典", "浓烈", "醇厚"]
  },
  {
    id: 6,
    name: "玛格丽特",
    nameEn: "Margarita",
    base: "龙舌兰",
    baseEn: "Tequila",
    ingredients: "龙舌兰 45ml、君度橙酒 15ml、青柠汁 20ml、杯口盐边",
    steps: "加冰摇匀，滤入盐边杯，青柠装饰",
    flavor: "龙舌兰草本香，青柠酸 + 盐边咸鲜，酸甜微咸",
    tags: ["经典", "酸酒", "咸鲜"]
  },
  {
    id: 7,
    name: "龙舌兰日出",
    nameEn: "Tequila Sunrise",
    base: "龙舌兰",
    baseEn: "Tequila",
    ingredients: "龙舌兰 45ml、橙汁补满、红石榴糖浆 10ml",
    steps: "加冰，入龙舌兰 + 橙汁，最后沉石榴糖浆",
    flavor: "龙舌兰清爽，橙汁甜香，果味浓郁，颜值高",
    tags: ["甜美", "果味", "高颜值"]
  },
  {
    id: 8,
    name: "血腥玛丽",
    nameEn: "Bloody Mary",
    base: "伏特加",
    baseEn: "Vodka",
    ingredients: "伏特加 45ml、番茄汁 100ml、辣酱油、盐、胡椒、西芹",
    steps: "加冰搅匀，西芹 + 柠檬装饰",
    flavor: "伏特加纯净，番茄咸鲜微辣，咸香醇厚",
    tags: ["咸香", "独特", "微辣"]
  },
  {
    id: 9,
    name: "新加坡司令",
    nameEn: "Singapore Sling",
    base: "金酒",
    baseEn: "Gin",
    ingredients: "金酒 30ml、樱桃白兰地 15ml、柠檬汁 20ml、红石榴糖浆 10ml、苏打水",
    steps: "摇匀后滤杯，补苏打水",
    flavor: "果香浓郁，酸甜清爽，花香果香交织",
    tags: ["经典", "果香", "酸甜"]
  },
  {
    id: 10,
    name: "长岛冰茶",
    nameEn: "Long Island Iced Tea",
    base: "混合基酒",
    baseEn: "Mixed",
    ingredients: "伏特加/金酒/朗姆/龙舌兰/君度各 15ml、柠檬汁 20ml、糖浆 10ml、可乐补满",
    steps: "基酒 + 酸甜摇匀，倒杯，可乐补顶",
    flavor: "酸甜顺口，无茶味，酒感隐藏，后劲足",
    tags: ["浓烈", "后劲足", "经典"]
  },
  {
    id: 11,
    name: "蓝色夏威夷",
    nameEn: "Blue Hawaii",
    base: "朗姆酒",
    baseEn: "Rum",
    ingredients: "白朗姆 30ml、蓝橙力娇 15ml、菠萝汁 60ml、椰浆 30ml",
    steps: "加冰摇匀，菠萝片装饰",
    flavor: "朗姆 + 椰香 + 菠萝，热带果香，甜润顺滑",
    tags: ["热带", "甜美", "高颜值"]
  },
  {
    id: 12,
    name: "椰林飘香",
    nameEn: "Piña Colada",
    base: "朗姆酒",
    baseEn: "Rum",
    ingredients: "白朗姆 45ml、菠萝汁 60ml、椰浆 30ml",
    steps: "加冰摇匀，菠萝 + 樱桃装饰",
    flavor: "菠萝椰香浓郁，甜柔顺滑，经典热带风味",
    tags: ["热带", "经典", "甜美"]
  },
  {
    id: 13,
    name: "大都会",
    nameEn: "Cosmopolitan",
    base: "伏特加",
    baseEn: "Vodka",
    ingredients: "伏特加 30ml、君度 15ml、青柠汁 10ml、红蔓越莓汁 30ml",
    steps: "摇匀滤杯，橙皮装饰",
    flavor: "蔓越莓酸甜 + 橙香，酸甜清爽，优雅柔和",
    tags: ["现代", "优雅", "酸甜"]
  },
  {
    id: 14,
    name: "神风特攻队",
    nameEn: "Kamikaze",
    base: "伏特加",
    baseEn: "Vodka",
    ingredients: "伏特加 20ml、君度 20ml、青柠汁 20ml",
    steps: "加冰摇匀",
    flavor: "酸甜清爽，橙香 + 青柠酸，干净利落",
    tags: ["酸酒", "清爽", "利落"]
  },
  {
    id: 15,
    name: "侧车",
    nameEn: "Sidecar",
    base: "白兰地",
    baseEn: "Brandy",
    ingredients: "白兰地 40ml、君度 15ml、柠檬汁 20ml",
    steps: "摇匀滤杯，糖边可选",
    flavor: "白兰地醇厚，橙香酸甜，顺滑浓郁",
    tags: ["经典", "酸酒", "醇厚"]
  },
  {
    id: 16,
    name: "古典杯",
    nameEn: "Old Fashioned",
    base: "威士忌",
    baseEn: "Whiskey",
    ingredients: "波本威士忌 45ml、方糖 1 块、苦精 2 滴、水少许",
    steps: "糖 + 苦精 + 水捣化，加冰 + 威士忌，橙皮装饰",
    flavor: "威士忌醇厚，微甜微苦，经典木质香",
    tags: ["经典", "醇厚", "浓烈"]
  },
  {
    id: 17,
    name: "尼格罗尼",
    nameEn: "Negroni",
    base: "金酒",
    baseEn: "Gin",
    ingredients: "金酒 30ml、金巴利 30ml、甜苦艾酒 30ml",
    steps: "加冰搅拌，橙皮装饰",
    flavor: "苦甜平衡，草本柑橘香，醇厚微苦",
    tags: ["经典", "苦甜", "醇厚"]
  },
  {
    id: 18,
    name: "教父",
    nameEn: "Godfather",
    base: "威士忌",
    baseEn: "Whiskey",
    ingredients: "苏格兰威士忌 40ml、杏仁力娇 20ml",
    steps: "加冰搅拌",
    flavor: "威士忌醇厚 + 杏仁甜香，温润顺滑，浓郁厚重",
    tags: ["经典", "醇厚", "甜美"]
  },
  {
    id: 19,
    name: "教母",
    nameEn: "Godmother",
    base: "伏特加",
    baseEn: "Vodka",
    ingredients: "伏特加 40ml、杏仁力娇 20ml",
    steps: "加冰搅拌",
    flavor: "伏特加纯净 + 杏仁甜香，清爽温润，柔和易饮",
    tags: ["甜美", "柔和", "易饮"]
  },
  {
    id: 20,
    name: "黑俄罗斯",
    nameEn: "Black Russian",
    base: "伏特加",
    baseEn: "Vodka",
    ingredients: "伏特加 40ml、咖啡力娇 20ml",
    steps: "加冰搅匀",
    flavor: "伏特加 + 咖啡甜香，醇厚浓郁，苦甜平衡",
    tags: ["经典", "咖啡", "醇厚"]
  },
  {
    id: 21,
    name: "白俄罗斯",
    nameEn: "White Russian",
    base: "伏特加",
    baseEn: "Vodka",
    ingredients: "伏特加 40ml、咖啡力娇 20ml、淡奶油 30ml",
    steps: "先搅匀前两者，最后浮奶油",
    flavor: "咖啡 + 奶香，甜润顺滑，醇厚不腻",
    tags: ["经典", "咖啡", "甜美"]
  },
  {
    id: 22,
    name: "薄荷茱莉普",
    nameEn: "Mint Julep",
    base: "威士忌",
    baseEn: "Whiskey",
    ingredients: "波本威士忌 60ml、薄荷叶、糖浆 15ml",
    steps: "薄荷叶 + 糖浆轻捣，加冰 + 威士忌",
    flavor: "薄荷清凉 + 波本醇香，清爽解暑，甜润柔和",
    tags: ["经典", "清凉", "柔和"]
  },
  {
    id: 23,
    name: "香槟鸡尾酒",
    nameEn: "Champagne Cocktail",
    base: "香槟",
    baseEn: "Champagne",
    ingredients: "白兰地 10ml、香槟补满、方糖 + 苦精 1 滴",
    steps: "糖 + 苦精放杯底，入白兰地，倒香槟",
    flavor: "香槟果香 + 白兰地醇厚，微甜清爽，优雅",
    tags: ["优雅", "气泡", "经典"]
  },
  {
    id: 24,
    name: "含羞草",
    nameEn: "Mimosa",
    base: "香槟",
    baseEn: "Champagne",
    ingredients: "香槟 60ml、橙汁 60ml",
    steps: "冰杯，先橙汁后香槟",
    flavor: "香槟气泡 + 橙汁甜香，清新柔和，果香淡雅",
    tags: ["清新", "气泡", "优雅"]
  },
  {
    id: 25,
    name: "贝利尼",
    nameEn: "Bellini",
    base: "香槟",
    baseEn: "Champagne",
    ingredients: "普罗塞克/香槟 70ml、水蜜桃泥 30ml",
    steps: "桃泥入杯，轻倒起泡酒",
    flavor: "水蜜桃甜香 + 起泡酒清爽，温润香甜",
    tags: ["优雅", "果香", "甜美"]
  },
  {
    id: 26,
    name: "螺丝起子",
    nameEn: "Screwdriver",
    base: "伏特加",
    baseEn: "Vodka",
    ingredients: "伏特加 45ml、橙汁补满",
    steps: "加冰搅匀",
    flavor: "伏特加 + 橙汁甜香，简单顺口，清爽果味",
    tags: ["简单", "果味", "清爽"]
  },
  {
    id: 27,
    name: "咸狗",
    nameEn: "Salty Dog",
    base: "伏特加",
    baseEn: "Vodka",
    ingredients: "伏特加 45ml、西柚汁补满、杯口盐边",
    steps: "加冰搅匀",
    flavor: "西柚微苦果酸 + 盐边，咸鲜清爽，解腻开胃",
    tags: ["清爽", "咸鲜", "开胃"]
  },
  {
    id: 28,
    name: "金菲士",
    nameEn: "Gin Fizz",
    base: "金酒",
    baseEn: "Gin",
    ingredients: "金酒 45ml、柠檬汁 25ml、糖浆 15ml、苏打水",
    steps: "摇匀后滤杯，补苏打水",
    flavor: "金酒 + 柠檬酸甜，气泡清爽，干爽清新",
    tags: ["经典", "气泡", "清爽"]
  },
  {
    id: 29,
    name: "汤姆柯林斯",
    nameEn: "Tom Collins",
    base: "金酒",
    baseEn: "Gin",
    ingredients: "金酒 45ml、柠檬汁 25ml、糖浆 15ml、苏打水",
    steps: "加冰，摇匀基酒 + 酸甜，补苏打水",
    flavor: "金酒清爽，酸甜带气泡，通透解腻",
    tags: ["经典", "清爽", "气泡"]
  },
  {
    id: 30,
    name: "锈钉",
    nameEn: "Rusty Nail",
    base: "威士忌",
    baseEn: "Whiskey",
    ingredients: "苏格兰威士忌 30ml、蜂蜜力娇 30ml",
    steps: "加冰搅拌",
    flavor: "威士忌 + 蜂蜜甜香，温润醇厚，柔和顺滑",
    tags: ["经典", "醇厚", "甜美"]
  },
  {
    id: 31,
    name: "法国 75",
    nameEn: "French 75",
    base: "金酒",
    baseEn: "Gin",
    ingredients: "金酒 25ml、香槟补满、柠檬汁 15ml、糖浆 10ml",
    steps: "摇匀金酒 + 酸甜，倒杯，补香槟",
    flavor: "金酒 + 香槟气泡，酸甜清爽，优雅明亮",
    tags: ["经典", "优雅", "气泡"]
  },
  {
    id: 32,
    name: "天使之吻",
    nameEn: "Angel's Kiss",
    base: "白兰地",
    baseEn: "Brandy",
    ingredients: "可可奶油力娇 20ml、白兰地 10ml、淡奶油浮顶",
    steps: "分层，樱桃装饰",
    flavor: "可可奶香 + 白兰地，甜润绵密，温柔醇厚",
    tags: ["甜美", "分层", "温柔"]
  },
  {
    id: 33,
    name: "红粉佳人",
    nameEn: "Pink Lady",
    base: "金酒",
    baseEn: "Gin",
    ingredients: "金酒 30ml、红石榴糖浆 10ml、蛋清、柠檬汁 15ml",
    steps: "加冰摇匀",
    flavor: "金酒 + 石榴甜香，酸甜柔滑，优雅粉嫩",
    tags: ["经典", "优雅", "甜美"]
  },
  {
    id: 34,
    name: "蚱蜢",
    nameEn: "Grasshopper",
    base: "利口酒",
    baseEn: "Liqueur",
    ingredients: "绿薄荷力娇 25ml、可可奶油力娇 25ml、淡奶油 25ml",
    steps: "摇匀滤杯",
    flavor: "薄荷 + 可可奶香，甜润清爽，顺滑柔和",
    tags: ["甜美", "薄荷", "顺滑"]
  },
  {
    id: 35,
    name: "黑刺李金酒菲士",
    nameEn: "Sloe Gin Fizz",
    base: "金酒",
    baseEn: "Gin",
    ingredients: "黑刺李金酒 45ml、柠檬汁 20ml、糖浆 10ml、苏打水",
    steps: "摇匀后滤杯，补苏打水",
    flavor: "黑刺李果香 + 酸甜气泡，温润清爽",
    tags: ["果香", "气泡", "清爽"]
  }
];
